### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by BirknerAlex** [BirknerAlex/overstream#1]
This are the todos for the initial version 1.0.

Base
- [ ] Working Plugin Engine Communication with Websocket via Queues
- [ ] Initial Plugin Framework (Run each Plugin as own Thread)
- [ ] HTML Template Engine
- [ ] Javascript Framework for Notifications
- [ ] Javascript Plugin Communication
- [ ] Compiling (?)

Default Plugins
- [ ] Twitch Chat
- [ ] Twitch Notifications (Follows, Subs)
- [ ] Twitter Hashtag Stream
- [ ] Twitch Stats Update (Viewers, Followers, Users in Chat)
- [ ] URL JSON Pusher (Downloading JSON and pushing via Websocket including auto-reload)
